spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tracker_db?useSSL=false&serverTimezone=UTC
    username: root
    password: nt7n7xrtpy
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
